export NCCL_DEBUG=""
pip3 install git+https://github.com/t1101675/transformers.git@data_selection
pip3 install git+https://github.com/EleutherAI/lm-evaluation-harness.git@15ffb0dafa9c869c7436ba9a3cf3067ac4c9d846
pip3 install torch
pip3 install deepspeed
pip3 install numerize
pip3 install torchtyping
pip3 install rich
pip3 install accelerate
pip3 install datasets
pip3 install sentencepiece
pip3 install peft
pip3 install matplotlib
pip3 install wandb
pip3 install cvxpy
pip3 install h5py
pip3 install scikit-learn
pip3 install Levenshtein
pip3 install xformers==0.0.26.post1
